import type { Metadata, NextPage } from 'next'
import { type ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'About Page',
  description: 'Generated by create next app',
}

interface Props {
  children?: ReactNode
}

const About: NextPage<Props> = async (props) => {
  console.log('About page', props)

  const data = await fetch('http://localhost:3000/home/api', {
    method: 'post',
  })

  return <>
    <h1 className="text-red" >About</h1>

  </>
}

export default About
