import Script from 'next/script'
import type { Metadata } from 'next'

import '@/styles/global.css'

export const metadata: Metadata = {
  title: 'Next APP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh">
      <body className="font-sans dark:text-white w-100vw h-100vh overflow-auto">
        {children}
        <Footer />
      </body>
      <Script src="/theme.js" />
    </html>
  )
}
