import Script from 'next/script'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/global.css'
import type { ReactNode } from 'react'

interface Props {
  children?: ReactNode
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next APP',
  description: 'Generated by create next app',
}

export default function RootLayout(props: Props) {
  const {
    children,
  } = props

  return (
    <html lang="zh" className="dark">
      <Script src="/theme.js" />

      <body className={`font-sans dark:text-white dark:bg-black ${inter.className}`}>
        <main className="w-100vw h-[calc(100vh-24px)] overflow-auto p-5px">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
